name:    luna-bus-logger
version: 0.1.0.0
license: AGPLv3
author:  Luna Team <contact@luna-lang.org>

default-extensions:
  - NoImplicitPrelude
  - LambdaCase

ghc-options:
    -Wall

dependencies:
  - base
  - binary
  - bytestring
  - containers
  - either
  - errors
  - m-logger
  - mtl
  - optparse-applicative
  - prologue
  - protocol-buffers
  - time
  - transformers
  - zeromq4-haskell >= 0.4
  - zmq-bus
  - zmq-bus-config

executables:
  luna-bus-logger:
    source-dirs: src-app
    main:        Main.hs
